# This file was generated by GoReleaser. DO NOT EDIT.
cask "stockroom" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "e48654f09726b01417c2a0c3aeb15f9cab0895891c23c005490d113bb55bb14b"
      url "https://github.com/Kathir-D/Stockroom/releases/download/v#{version}/stockroom_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa7b86317c26999b88342ba0852cc86faf3770acd637140b8ee58ea9cd4f530a"
      url "https://github.com/Kathir-D/Stockroom/releases/download/v#{version}/stockroom_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8fa6bba51d34e25f01769a67819be802fa19abefb9cb0d9e26b0dc99d10d1e97"
      url "https://github.com/Kathir-D/Stockroom/releases/download/v#{version}/stockroom_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c5b2e5b8573427db40ca3a0d2540be6812ffc16de7962a6fe58ea89e47bfa70"
      url "https://github.com/Kathir-D/Stockroom/releases/download/v#{version}/stockroom_linux_amd64.tar.gz"
    end
  end

  name "stockroom"
  desc "Equipment checkout for a school media department"
  homepage "https://github.com/Kathir-D/Stockroom"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "postgresql@17",
      "rclone",
    ]

  binary "stockroom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stockroom"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Finish the install with:

      stockroom setup

    It creates the database, writes the config and starts Stockroom at boot.
    It asks for your password once, to install the LaunchDaemons.
  EOS
end
